i3-config: /home/hjw/.config/i3/config
polybar-config: /home/hjw/.config/polybar/config
xresources: /home/hjw/.Xresources
nitrogen-config: /home/hjw/.config/nitrogen/bg-saved.cfg
wallpaper-path: /home/hjw/.config/nitrogen/
